export interface KnowledgeChunk {
  id: string
  subject: string
  year: string
  topic: string
  unit: string
  knowledge_point: string
  learning_objective: string
  level: number
  applicable_question_types: string[]
  source: string
}

export const KNOWLEDGE_BASE: KnowledgeChunk[] = [
  // ── 範疇一：健康與生活 ──────────────────────────────────────────
  {
    id: 'GS_P3_001',
    subject: '常識科',
    year: 'P3',
    topic: '健康與生活',
    unit: '個人衛生與健康習慣',
    knowledge_point: '正確洗手的方法與重要性',
    learning_objective: '認識正確的洗手步驟（濕、搓、沖、捧、抹），了解洗手在預防疾病傳播中的重要作用。',
    level: 1,
    applicable_question_types: ['mc', 'tf', 'fill', 'short'],
    source: '教育局《小學常識科課程指引（2017）》',
  },
  {
    id: 'GS_P3_002',
    subject: '常識科',
    year: 'P3',
    topic: '健康與生活',
    unit: '個人衛生與健康習慣',
    knowledge_point: '均衡飲食的基本概念與健康影響',
    learning_objective: '認識均衡飲食的概念，了解各類食物（穀物、蔬果、蛋白質、乳製品等）對身體的作用，能辨別健康與不健康的飲食習慣。',
    level: 1,
    applicable_question_types: ['mc', 'classify', 'fill', 'tf'],
    source: '教育局《小學常識科課程指引（2017）》',
  },
  {
    id: 'GS_P3_003',
    subject: '常識科',
    year: 'P3',
    topic: '健康與生活',
    unit: '個人衛生與健康習慣',
    knowledge_point: '充足休息、睡眠與適量運動對健康的幫助',
    learning_objective: '了解充足睡眠（小學生每天約9-11小時）、適量運動對身體和精神健康的好處，能制定簡單的健康生活計劃。',
    level: 1,
    applicable_question_types: ['mc', 'fill', 'short'],
    source: '教育局《小學常識科課程指引（2017）》',
  },
  {
    id: 'GS_P3_004',
    subject: '常識科',
    year: 'P3',
    topic: '健康與生活',
    unit: '個人衛生與健康習慣',
    knowledge_point: '預防常見疾病的簡單方法',
    learning_objective: '認識預防感冒、流感等常見疾病的方法，包括接種疫苗、保持個人衛生、避免接觸病源等。',
    level: 1,
    applicable_question_types: ['mc', 'tf', 'match', 'short'],
    source: '教育局《小學常識科課程指引（2017）》',
  },
  {
    id: 'GS_P3_005',
    subject: '常識科',
    year: 'P3',
    topic: '健康與生活',
    unit: '情緒管理與人際關係',
    knowledge_point: '辨識常見情緒及表達方法',
    learning_objective: '能辨識喜、怒、哀、懼等常見情緒，了解情緒的成因，學習以適當方式表達情緒（如言語表達、繪畫、運動等）。',
    level: 1,
    applicable_question_types: ['mc', 'tf', 'fill', 'short'],
    source: '教育局《小學常識科課程指引（2017）》',
  },
  {
    id: 'GS_P3_006',
    subject: '常識科',
    year: 'P3',
    topic: '健康與生活',
    unit: '情緒管理與人際關係',
    knowledge_point: '與家人、朋友和諧相處的基本方法',
    learning_objective: '認識維繫良好家庭和朋友關係的方法，包括互相尊重、分享、溝通及體諒他人的感受。',
    level: 1,
    applicable_question_types: ['mc', 'tf', 'short'],
    source: '教育局《小學常識科課程指引（2017）》',
  },
  {
    id: 'GS_P3_007',
    subject: '常識科',
    year: 'P3',
    topic: '健康與生活',
    unit: '情緒管理與人際關係',
    knowledge_point: '解決簡單人際衝突的方法',
    learning_objective: '了解人際衝突的常見原因，學習以和平方式解決衝突，包括冷靜溝通、尋求調解、妥協等方法。',
    level: 1,
    applicable_question_types: ['mc', 'short', 'match'],
    source: '教育局《小學常識科課程指引（2017）》',
  },
  {
    id: 'GS_P3_008',
    subject: '常識科',
    year: 'P3',
    topic: '健康與生活',
    unit: '安全意識與自我保護',
    knowledge_point: '家居及校園常見安全隱患與預防',
    learning_objective: '能辨識家居（如廚房、浴室）及校園中的常見安全隱患，了解預防意外的方法及發生意外時的應對措施。',
    level: 1,
    applicable_question_types: ['mc', 'tf', 'classify', 'short'],
    source: '教育局《小學常識科課程指引（2017）》',
  },
  {
    id: 'GS_P3_009',
    subject: '常識科',
    year: 'P3',
    topic: '健康與生活',
    unit: '安全意識與自我保護',
    knowledge_point: '陌生人及網絡安全的基本認識',
    learning_objective: '了解與陌生人接觸的安全守則，認識網絡安全的基本知識，包括保護個人資料、辨識網絡危險及適當使用互聯網。',
    level: 1,
    applicable_question_types: ['mc', 'tf', 'short'],
    source: '教育局《小學常識科課程指引（2017）》',
  },
  {
    id: 'GS_P3_010',
    subject: '常識科',
    year: 'P3',
    topic: '健康與生活',
    unit: '安全意識與自我保護',
    knowledge_point: '求助方法與緊急求救知識',
    learning_objective: '認識緊急求救電話（999、999、1878000等），了解在不同緊急情況下的求助方法，能描述自己的位置及情況。',
    level: 1,
    applicable_question_types: ['mc', 'fill', 'short'],
    source: '教育局《小學常識科課程指引（2017）》',
  },
  // ── 範疇二：環境與生活 ──────────────────────────────────────────
  {
    id: 'GS_P3_011',
    subject: '常識科',
    year: 'P3',
    topic: '環境與生活',
    unit: '社區環境與設施',
    knowledge_point: '社區主要設施與服務的功能',
    learning_objective: '認識社區內常見設施（如圖書館、郵局、診所、消防局等）的功能及其提供的服務，了解這些設施如何滿足居民的日常需要。',
    level: 1,
    applicable_question_types: ['mc', 'match', 'fill', 'classify'],
    source: '教育局《小學常識科課程指引（2017）》',
  },
  {
    id: 'GS_P3_012',
    subject: '常識科',
    year: 'P3',
    topic: '環境與生活',
    unit: '社區環境與設施',
    knowledge_point: '愛護社區環境與公共設施的責任',
    learning_objective: '了解愛護社區環境和公共設施的重要性，認識破壞公物的後果，培養對社區的歸屬感和責任感。',
    level: 1,
    applicable_question_types: ['mc', 'tf', 'short'],
    source: '教育局《小學常識科課程指引（2017）》',
  },
  {
    id: 'GS_P3_013',
    subject: '常識科',
    year: 'P3',
    topic: '環境與生活',
    unit: '社區環境與設施',
    knowledge_point: '社區清潔與廢物分類的基本概念',
    learning_objective: '認識廢物分類的方法（紙張、金屬、塑膠、玻璃等），了解垃圾分類對環境保護的意義，能在日常生活中實踐廢物分類。',
    level: 1,
    applicable_question_types: ['mc', 'classify', 'tf', 'short'],
    source: '教育局《小學常識科課程指引（2017）》',
  },
  {
    id: 'GS_P3_014',
    subject: '常識科',
    year: 'P3',
    topic: '環境與生活',
    unit: '自然環境與保育',
    knowledge_point: '香港常見自然環境與動植物',
    learning_objective: '認識香港的自然環境特色，了解香港常見的動植物種類，能辨識部分本地常見動植物。',
    level: 1,
    applicable_question_types: ['mc', 'match', 'fill', 'short'],
    source: '教育局《小學常識科課程指引（2017）》',
  },
  {
    id: 'GS_P3_015',
    subject: '常識科',
    year: 'P3',
    topic: '環境與生活',
    unit: '自然環境與保育',
    knowledge_point: '保護自然環境的簡單方法',
    learning_objective: '了解保護自然環境的重要性，認識在日常生活中保護環境的具體方法，如減少污染、保護野生動物等。',
    level: 1,
    applicable_question_types: ['mc', 'tf', 'short'],
    source: '教育局《小學常識科課程指引（2017）》',
  },
  {
    id: 'GS_P3_016',
    subject: '常識科',
    year: 'P3',
    topic: '環境與生活',
    unit: '自然環境與保育',
    knowledge_point: '人類活動對自然環境的影響',
    learning_objective: '認識人類活動（如工業生產、過度開發、廢物排放等）對自然環境造成的影響，了解環境破壞的後果。',
    level: 1,
    applicable_question_types: ['mc', 'tf', 'short'],
    source: '教育局《小學常識科課程指引（2017）》',
  },
  {
    id: 'GS_P3_017',
    subject: '常識科',
    year: 'P3',
    topic: '環境與生活',
    unit: '資源節約與環保生活',
    knowledge_point: '節約用水、用電的日常方法',
    learning_objective: '了解水和電是珍貴資源，認識在日常生活中節約用水（如關緊水龍頭、縮短淋浴時間）和節約用電（如關燈、使用節能電器）的具體方法。',
    level: 1,
    applicable_question_types: ['mc', 'tf', 'fill', 'short'],
    source: '教育局《小學常識科課程指引（2017）》',
  },
  {
    id: 'GS_P3_018',
    subject: '常識科',
    year: 'P3',
    topic: '環境與生活',
    unit: '資源節約與環保生活',
    knowledge_point: '減少使用、循環再用及廢物利用',
    learning_objective: '認識「減少使用、循環再用、廢物利用」（3R）的環保概念，了解如何在日常生活中實踐，減少廢物產生。',
    level: 1,
    applicable_question_types: ['mc', 'classify', 'short'],
    source: '教育局《小學常識科課程指引（2017）》',
  },
  {
    id: 'GS_P3_019',
    subject: '常識科',
    year: 'P3',
    topic: '環境與生活',
    unit: '資源節約與環保生活',
    knowledge_point: '使用公共交通工具的環保意義',
    learning_objective: '了解使用公共交通工具相比私家車對環境的好處，包括減少廢氣排放、節省能源及減少交通擠塞。',
    level: 1,
    applicable_question_types: ['mc', 'tf', 'short'],
    source: '教育局《小學常識科課程指引（2017）》',
  },
  // ── 範疇三：理財與經濟 ──────────────────────────────────────────
  {
    id: 'GS_P3_020',
    subject: '常識科',
    year: 'P3',
    topic: '理財與經濟',
    unit: '消費與理財基礎',
    knowledge_point: '需要與想要的區分及消費決定',
    learning_objective: '分辨「需要」（生活必需品）與「想要」（非必需的欲望），並能根據輕重緩急作出合理的消費決定，培養理性消費習慣。',
    level: 1,
    applicable_question_types: ['mc', 'tf', 'fill', 'short'],
    source: '教育局《小學常識科課程指引（2017）》',
  },
  {
    id: 'GS_P3_021',
    subject: '常識科',
    year: 'P3',
    topic: '理財與經濟',
    unit: '消費與理財基礎',
    knowledge_point: '消費者的基本權利與義務',
    learning_objective: '了解消費者享有的基本權利（如獲得安全產品、準確資訊、公平交易等）及應盡的義務（如誠實付款、合理使用商品等）。',
    level: 1,
    applicable_question_types: ['mc', 'tf', 'match', 'short'],
    source: '教育局《小學常識科課程指引（2017）》',
  },
  {
    id: 'GS_P3_022',
    subject: '常識科',
    year: 'P3',
    topic: '理財與經濟',
    unit: '消費與理財基礎',
    knowledge_point: '簡單儲蓄與金錢管理概念',
    learning_objective: '認識儲蓄的重要性，了解簡單的金錢管理方法，包括記錄收支、制定預算及養成儲蓄習慣。',
    level: 1,
    applicable_question_types: ['mc', 'fill', 'short'],
    source: '教育局《小學常識科課程指引（2017）》',
  },
  {
    id: 'GS_P3_023',
    subject: '常識科',
    year: 'P3',
    topic: '理財與經濟',
    unit: '消費與理財基礎',
    knowledge_point: '精明消費的考慮因素',
    learning_objective: '掌握精明消費的方法，包括比較價格與品質、查看產品標籤、認識消費者保障機構，以及避免衝動消費的策略。',
    level: 1,
    applicable_question_types: ['mc', 'tf', 'fill', 'short'],
    source: '教育局《小學常識科課程指引（2017）》',
  },
  {
    id: 'GS_P3_024',
    subject: '常識科',
    year: 'P3',
    topic: '理財與經濟',
    unit: '社區經濟與交易',
    knowledge_point: '社區常見交易場所與服務',
    learning_objective: '認識社區內不同類型的交易場所（如超級市場、街市、商場、網上商店等）及其特點，了解各種付款方式（現金、八達通、信用卡等）。',
    level: 1,
    applicable_question_types: ['mc', 'match', 'fill', 'classify'],
    source: '教育局《小學常識科課程指引（2017）》',
  },
  {
    id: 'GS_P3_025',
    subject: '常識科',
    year: 'P3',
    topic: '理財與經濟',
    unit: '社區經濟與交易',
    knowledge_point: '簡單買賣與找續計算',
    learning_objective: '能進行簡單的買賣計算，包括計算總價、找續金額，以及判斷是否得到正確找續，培養基本的數學應用能力。',
    level: 1,
    applicable_question_types: ['mc', 'fill', 'short'],
    source: '教育局《小學常識科課程指引（2017）》',
  },
  // ── 範疇四：社會與公民 ──────────────────────────────────────────
  {
    id: 'GS_P3_026',
    subject: '常識科',
    year: 'P3',
    topic: '社會與公民',
    unit: '家庭、學校與社區角色',
    knowledge_point: '家庭成員的角色與責任',
    learning_objective: '認識家庭成員各自的角色和責任，了解家庭成員之間互相關愛、分擔家務的重要性，培養對家庭的責任感。',
    level: 1,
    applicable_question_types: ['mc', 'match', 'short'],
    source: '教育局《小學常識科課程指引（2017）》',
  },
  {
    id: 'GS_P3_027',
    subject: '常識科',
    year: 'P3',
    topic: '社會與公民',
    unit: '家庭、學校與社區角色',
    knowledge_point: '學校生活中的規則與合作',
    learning_objective: '了解學校規則的重要性，認識在學校生活中與同學合作、互相尊重的方法，培養良好的公民意識。',
    level: 1,
    applicable_question_types: ['mc', 'tf', 'short'],
    source: '教育局《小學常識科課程指引（2017）》',
  },
  {
    id: 'GS_P3_028',
    subject: '常識科',
    year: 'P3',
    topic: '社會與公民',
    unit: '家庭、學校與社區角色',
    knowledge_point: '社區成員的互助與貢獻',
    learning_objective: '認識社區中不同成員（如義工、社區服務人員等）的貢獻，了解社區成員互助合作的重要性，培養服務社區的精神。',
    level: 1,
    applicable_question_types: ['mc', 'short', 'match'],
    source: '教育局《小學常識科課程指引（2017）》',
  },
  {
    id: 'GS_P3_029',
    subject: '常識科',
    year: 'P3',
    topic: '社會與公民',
    unit: '公民權利與責任',
    knowledge_point: '遵守規則與尊重他人的重要性',
    learning_objective: '了解在社會生活中遵守規則的重要性，認識尊重他人的具體表現，培養良好的公民品德和社會責任感。',
    level: 1,
    applicable_question_types: ['mc', 'tf', 'short'],
    source: '教育局《小學常識科課程指引（2017）》',
  },
  {
    id: 'GS_P3_030',
    subject: '常識科',
    year: 'P3',
    topic: '社會與公民',
    unit: '公民權利與責任',
    knowledge_point: '幫助他人與服務社區的意義',
    learning_objective: '了解幫助他人和服務社區的意義，認識義務工作的概念，培養關愛他人、回饋社會的精神。',
    level: 1,
    applicable_question_types: ['mc', 'tf', 'short'],
    source: '教育局《小學常識科課程指引（2017）》',
  },
  {
    id: 'GS_P3_031',
    subject: '常識科',
    year: 'P3',
    topic: '社會與公民',
    unit: '交通與公共服務',
    knowledge_point: '香港主要公共交通工具與使用方法',
    learning_objective: '認識香港主要的公共交通工具（港鐵、巴士、小巴、渡輪、電車、的士等），了解各種交通工具的特點、路線及購票/付款方式。',
    level: 1,
    applicable_question_types: ['mc', 'match', 'fill', 'classify'],
    source: '教育局《小學常識科課程指引（2017）》',
  },
  {
    id: 'GS_P3_032',
    subject: '常識科',
    year: 'P3',
    topic: '社會與公民',
    unit: '交通與公共服務',
    knowledge_point: '乘搭交通工具的安全守則與禮貌',
    learning_objective: '掌握乘搭各種交通工具時應遵守的安全守則（如扶穩手把、不把頭手伸出窗外等）及應有的禮貌行為（如讓座、排隊候車等）。',
    level: 1,
    applicable_question_types: ['mc', 'tf', 'fill', 'short'],
    source: '教育局《小學常識科課程指引（2017）》',
  },
  {
    id: 'GS_P3_033',
    subject: '常識科',
    year: 'P3',
    topic: '社會與公民',
    unit: '交通與公共服務',
    knowledge_point: '選擇合適交通工具的考慮因素',
    learning_objective: '能根據目的地、時間、費用、便利程度等因素，選擇最合適的交通工具，並能規劃簡單的交通路線。',
    level: 1,
    applicable_question_types: ['mc', 'tf', 'fill', 'short'],
    source: '教育局《小學常識科課程指引（2017）》',
  },
  // ── 範疇五：國家與我 ────────────────────────────────────────────
  {
    id: 'GS_P3_034',
    subject: '常識科',
    year: 'P3',
    topic: '國家與我',
    unit: '中華文化認識',
    knowledge_point: '中國傳統節日與習俗',
    learning_objective: '認識中國主要傳統節日（如農曆新年、中秋節、端午節等）的由來、習俗及慶祝方式，了解傳統節日對中華文化的意義。',
    level: 1,
    applicable_question_types: ['mc', 'match', 'fill', 'short'],
    source: '教育局《小學常識科課程指引（2017）》',
  },
  {
    id: 'GS_P3_035',
    subject: '常識科',
    year: 'P3',
    topic: '國家與我',
    unit: '中華文化認識',
    knowledge_point: '中華傳統美德與價值觀',
    learning_objective: '認識中華傳統美德（如孝順、誠信、勤勞、謙遜等），了解這些價值觀在現代生活中的意義，培養對中華文化的認同感。',
    level: 1,
    applicable_question_types: ['mc', 'tf', 'short'],
    source: '教育局《小學常識科課程指引（2017）》',
  },
  {
    id: 'GS_P3_036',
    subject: '常識科',
    year: 'P3',
    topic: '國家與我',
    unit: '中華文化認識',
    knowledge_point: '中國地理與著名景點初步認識',
    learning_objective: '初步認識中國的地理特色（如長江、黃河、長城等），了解部分著名景點的位置和特色，培養對祖國的認識和興趣。',
    level: 1,
    applicable_question_types: ['mc', 'match', 'fill', 'classify'],
    source: '教育局《小學常識科課程指引（2017）》',
  },
  {
    id: 'GS_P3_037',
    subject: '常識科',
    year: 'P3',
    topic: '國家與我',
    unit: '國家象徵與身份認同',
    knowledge_point: '國旗、國徽及國歌的意義',
    learning_objective: '認識中國國旗（五星紅旗）的設計含義、國徽的組成及國歌（義勇軍進行曲）的歷史背景，了解這些國家象徵的意義。',
    level: 1,
    applicable_question_types: ['mc', 'tf', 'fill', 'short'],
    source: '教育局《小學常識科課程指引（2017）》',
  },
  {
    id: 'GS_P3_038',
    subject: '常識科',
    year: 'P3',
    topic: '國家與我',
    unit: '國家象徵與身份認同',
    knowledge_point: '香港特別行政區的地位與特色',
    learning_objective: '了解香港作為中國特別行政區的地位，認識「一國兩制」的基本概念，了解香港的特色（如中西文化交融、國際金融中心等）。',
    level: 1,
    applicable_question_types: ['mc', 'tf', 'short'],
    source: '教育局《小學常識科課程指引（2017）》',
  },
  {
    id: 'GS_P3_039',
    subject: '常識科',
    year: 'P3',
    topic: '國家與我',
    unit: '國家象徵與身份認同',
    knowledge_point: '作為中國人的自豪感與責任',
    learning_objective: '培養對中國人身份的認同感和自豪感，了解作為中國公民的責任，包括愛護國家、遵守法律及為國家發展作出貢獻。',
    level: 1,
    applicable_question_types: ['mc', 'tf', 'short'],
    source: '教育局《小學常識科課程指引（2017）》',
  },
  // ── 範疇六：世界與我 ────────────────────────────────────────────
  {
    id: 'GS_P3_040',
    subject: '常識科',
    year: 'P3',
    topic: '世界與我',
    unit: '世界多元文化',
    knowledge_point: '世界主要國家與地區的初步認識',
    learning_objective: '初步認識世界主要國家和地區的位置、特色（如語言、文化、著名景點等），培養對世界的好奇心和探索精神。',
    level: 1,
    applicable_question_types: ['mc', 'match', 'fill', 'classify'],
    source: '教育局《小學常識科課程指引（2017）》',
  },
  {
    id: 'GS_P3_041',
    subject: '常識科',
    year: 'P3',
    topic: '世界與我',
    unit: '世界多元文化',
    knowledge_point: '尊重不同文化與習俗的重要性',
    learning_objective: '了解世界各地文化和習俗的多樣性，認識尊重不同文化的重要性，培養開放包容的態度和跨文化理解能力。',
    level: 1,
    applicable_question_types: ['mc', 'tf', 'short'],
    source: '教育局《小學常識科課程指引（2017）》',
  },
  {
    id: 'GS_P3_042',
    subject: '常識科',
    year: 'P3',
    topic: '世界與我',
    unit: '資訊科技與日常生活',
    knowledge_point: '資訊科技在日常生活中的應用',
    learning_objective: '認識資訊科技（如互聯網、智能手機、電腦等）在日常生活各方面的應用（學習、通訊、娛樂、購物等），了解使用資訊科技的注意事項。',
    level: 1,
    applicable_question_types: ['mc', 'tf', 'fill', 'short'],
    source: '教育局《小學常識科課程指引（2017）》',
  },
  {
    id: 'GS_P3_043',
    subject: '常識科',
    year: 'P3',
    topic: '世界與我',
    unit: '資訊科技與日常生活',
    knowledge_point: '安全使用資訊科技的基本守則',
    learning_objective: '了解安全使用資訊科技的基本守則，包括保護個人資料、設定安全密碼、避免接觸不良內容及控制使用時間等。',
    level: 1,
    applicable_question_types: ['mc', 'tf', 'short'],
    source: '教育局《小學常識科課程指引（2017）》',
  },
  {
    id: 'GS_P3_044',
    subject: '常識科',
    year: 'P3',
    topic: '世界與我',
    unit: '資訊科技與日常生活',
    knowledge_point: '辨識可靠資訊的初步能力',
    learning_objective: '培養初步辨識網絡資訊可靠性的能力，了解假新聞和錯誤資訊的危害，學習核實資訊的基本方法。',
    level: 1,
    applicable_question_types: ['mc', 'tf', 'short'],
    source: '教育局《小學常識科課程指引（2017）》',
  },
  {
    id: 'GS_P3_045',
    subject: '常識科',
    year: 'P3',
    topic: '世界與我',
    unit: '全球視野與議題',
    knowledge_point: '全球環境問題與個人行動',
    learning_objective: '初步認識全球環境問題（如氣候變化、海洋污染、森林砍伐等），了解這些問題對人類和地球的影響，認識個人可以採取的環保行動。',
    level: 1,
    applicable_question_types: ['mc', 'tf', 'short'],
    source: '教育局《小學常識科課程指引（2017）》',
  },
  {
    id: 'GS_P3_046',
    subject: '常識科',
    year: 'P3',
    topic: '世界與我',
    unit: '全球視野與議題',
    knowledge_point: '世界和平與合作的基本概念',
    learning_objective: '了解世界和平的重要性，認識國際合作（如聯合國）在解決全球問題中的作用，培養對世界和平的關注和責任感。',
    level: 1,
    applicable_question_types: ['mc', 'tf', 'short'],
    source: '教育局《小學常識科課程指引（2017）》',
  },
]

export function getKnowledgeByIds(ids: string[]): KnowledgeChunk[] {
  return KNOWLEDGE_BASE.filter(k => ids.includes(k.id))
}
