export interface KnowledgeChunk {
  id: string
  subject: string
  year: string
  topic: string
  unit: string
  knowledge_point: string
  learning_objective: string
  level: number
  applicable_question_types: string[]
  source: string
}

export const KNOWLEDGE_BASE: KnowledgeChunk[] = [
  // ── 範疇一：健康與生活 ──────────────────────────────────────────
  {
    id: 'GS_P3_001',
    subject: '常識科',
    year: 'P3',
    topic: '健康與生活',
    unit: '個人衛生與健康習慣',
    knowledge_point: '正確洗手的方法與重要性',
    learning_objective: '認識正確的洗手步驟（濕、搓、沖、捧、抹），了解洗手在預防疾病傳播中的重要作用。',
    level: 1,
    applicable_question_types: ['mc', 'tf', 'fill', 'short'],
    source: '教育局《小學常識科課程指引（2017）》',
  },
  {
    id: 'GS_P3_002',
    subject: '常識科',
    year: 'P3',
    topic: '健康與生活',
    unit: '個人衛生與健康習慣',
    knowledge_point: '均衡飲食的基本概念與健康影響',
    learning_objective: '認識均衡飲食的概念，了解各類食物（穀物、蔬果、蛋白質、乳製品等）對身體的作用，能辨別健康與不健康的飲食習慣。',
    level: 1,
    applicable_question_types: ['mc', 'classify', 'fill', 'tf'],
    source: '教育局《小學常識科課程指引（2017）》',
  },
  {
    id: 'GS_P3_003',
    subject: '常識科',
    year: 'P3',
    topic: '健康與生活',
    unit: '個人衛生與健康習慣',
    knowledge_point: '充足休息、睡眠與適量運動對健康的幫助',
    learning_objective: '了解充足睡眠（小學生每天約9-11小時）、適量運動對身體和精神健康的好處，能制定簡單的健康生活計劃。',
    level: 1,
    applicable_question_types: ['mc', 'fill', 'short'],
    source: '教育局《小學常識科課程指引（2017）》',
  },
  {
    id: 'GS_P3_004',
    subject: '常識科',
    year: 'P3',
    topic: '健康與生活',
    unit: '個人衛生與健康習慣',
    knowledge_point: '預防常見疾病的簡單方法',
    learning_objective: '認識預防感冒、流感等常見疾病的方法，包括接種疫苗、保持個人衛生、避免接觸病源等。',
    level: 1,
    applicable_question_types: ['mc', 'tf', 'match', 'short'],
    source: '教育局《小學常識科課程指引（2017）》',
  },
  {
    id: 'GS_P3_005',
    subject: '常識科',
    year: 'P3',
    topic: '健康與生活',
    unit: '情緒管理與人際關係',
    knowledge_point: '辨識常見情緒及表達方法',
    learning_objective: '能辨識喜、怒、哀、懼等常見情緒，了解情緒的成因，學習以適當方式表達情緒（如言語表達、繪畫、運動等）。',
    level: 1,
    applicable_question_types: ['mc', 'tf', 'fill', 'short'],
    source: '教育局《小學常識科課程指引（2017）》',
  },
  {
    id: 'GS_P3_006',
    subject: '常識科',
    year: 'P3',
    topic: '健康與生活',
    unit: '情緒管理與人際關係',
    knowledge_point: '與家人、朋友和諧相處的基本方法',
    learning_objective: '認識維繫良好家庭和朋友關係的方法，包括互相尊重、分享、溝通及體諒他人的感受。',
    level: 1,
    applicable_question_types: ['mc', 'tf', 'short'],
    source: '教育局《小學常識科課程指引（2017）》',
  },
  {
    id: 'GS_P3_007',
    subject: '常識科',
    year: 'P3',
    topic: '健康與生活',
    unit: '情緒管理與人際關係',
    knowledge_point: '解決簡單人際衝突的方法',
    learning_objective: '了解人際衝突的常見原因，學習以和平方式解決衝突，包括冷靜溝通、尋求調解、妥協等方法。',
    level: 1,
    applicable_question_types: ['mc', 'short', 'match'],
    source: '教育局《小學常識科課程指引（2017）》',
  },
  {
    id: 'GS_P3_008',
    subject: '常識科',
    year: 'P3',
    topic: '健康與生活',
    unit: '安全意識與自我保護',
    knowledge_point: '家居及校園常見安全隱患與預防',
    learning_objective: '能辨識家居（如廚房、浴室）及校園中的常見安全隱患，了解預防意外的方法及發生意外時的應對措施。',
    level: 1,
    applicable_question_types: ['mc', 'tf', 'classify', 'short'],
    source: '教育局《小學常識科課程指引（2017）》',
  },
  {
    id: 'GS_P3_009',
    subject: '常識科',
    year: 'P3',
    topic: '健康與生活',
    unit: '安全意識與自我保護',
    knowledge_point: '陌生人及網絡安全的基本認識',
    learning_objective: '了解與陌生人接觸的安全守則，認識網絡安全的基本知識，包括保護個人資料、辨識網絡危險及適當使用互聯網。',
    level: 1,
    applicable_question_types: ['mc', 'tf', 'short'],
    source: '教育局《小學常識科課程指引（2017）》',
  },
  {
    id: 'GS_P3_010',
    subject: '常識科',
    year: 'P3',
    topic: '健康與生活',
    unit: '安全意識與自我保護',
    knowledge_point: '求助方法與緊急求救知識',
    learning_objective: '認識緊急求救電話（999、999、1878000等），了解在不同緊急情況下的求助方法，能描述自己的位置及情況。',
    level: 1,
    applicable_question_types: ['mc', 'fill', 'short'],
    source: '教育局《小學常識科課程指引（2017）》',
  },
  // ── 範疇二：環境與生活 ──────────────────────────────────────────
  {
    id: 'GS_P3_011',
    subject: '常識科',
    year: 'P3',
    topic: '環境與生活',
    unit: '社區環境與設施',
    knowledge_point: '社區主要設施與服務的功能',
    learning_objective: '認識社區內常見設施（如圖書館、郵局、診所、消防局等）的功能及其提供的服務，了解這些設施如何滿足居民的日常需要。',
    level: 1,
    applicable_question_types: ['mc', 'match', 'fill', 'classify'],
    source: '教育局《小學常識科課程指引（2017）》',
  },
  {
    id: 'GS_P3_012',
    subject: '常識科',
    year: 'P3',
    topic: '環境與生活',
    unit: '社區環境與設施',
    knowledge_point: '愛護社區環境與公共設施的責任',
    learning_objective: '了解愛護社區環境和公共設施的重要性，認識破壞公物的後果，培養對社區的歸屬感和責任感。',
    level: 1,
    applicable_question_types: ['mc', 'tf', 'short'],
    source: '教育局《小學常識科課程指引（2017）》',
  },
  {
    id: 'GS_P3_013',
    subject: '常識科',
    year: 'P3',
    topic: '環境與生活',
    unit: '社區環境與設施',
    knowledge_point: '社區清潔與廢物分類的基本概念',
    learning_objective: '認識廢物分類的方法（紙張、金屬、塑膠、玻璃等），了解垃圾分類對環境保護的意義，能在日常生活中實踐廢物分類。',
    level: 1,
    applicable_question_types: ['mc', 'classify', 'tf', 'short'],
    source: '教育局《小學常識科課程指引（2017）》',
  },
  {
    id: 'GS_P3_014',
    subject: '常識科',
    year: 'P3',
    topic: '環境與生活',
    unit: '自然環境與保育',
    knowledge_point: '香港常見自然環境與動植物',
    learning_objective: '認識香港的自然環境特色，了解香港常見的動植物種類，能辨識部分本地常見動植物。',
    level: 1,
    applicable_question_types: ['mc', 'match', 'fill', 'short'],
    source: '教育局《小學常識科課程指引（2017）》',
  },
  {
    id: 'GS_P3_015',
    subject: '常識科',
    year: 'P3',
    topic: '環境與生活',
    unit: '自然環境與保育',
    knowledge_point: '保護自然環境的簡單方法',
    learning_objective: '了解保護自然環境的重要性，認識在日常生活中保護環境的具體方法，如減少污染、保護野生動物等。',
    level: 1,
    applicable_question_types: ['mc', 'tf', 'short'],
    source: '教育局《小學常識科課程指引（2017）》',
  },
  {
    id: 'GS_P3_016',
    subject: '常識科',
    year: 'P3',
    topic: '環境與生活',
    unit: '自然環境與保育',
    knowledge_point: '人類活動對自然環境的影響',
    learning_objective: '認識人類活動（如工業生產、過度開發、廢物排放等）對自然環境造成的影響，了解環境破壞的後果。',
    level: 1,
    applicable_question_types: ['mc', 'tf', 'short'],
    source: '教育局《小學常識科課程指引（2017）》',
  },
  {
    id: 'GS_P3_017',
    subject: '常識科',
    year: 'P3',
    topic: '環境與生活',
    unit: '資源節約與環保生活',
    knowledge_point: '節約用水、用電的日常方法',
    learning_objective: '了解水和電是珍貴資源，認識在日常生活中節約用水（如關緊水龍頭、縮短淋浴時間）和節約用電（如關燈、使用節能電器）的具體方法。',
    level: 1,
    applicable_question_types: ['mc', 'tf', 'fill', 'short'],
    source: '教育局《小學常識科課程指引（2017）》',
  },
  {
    id: 'GS_P3_018',
    subject: '常識科',
    year: 'P3',
    topic: '環境與生活',
    unit: '資源節約與環保生活',
    knowledge_point: '減少使用、循環再用及廢物利用',
    learning_objective: '認識「減少使用、循環再用、廢物利用」（3R）的環保概念，了解如何在日常生活中實踐，減少廢物產生。',
    level: 1,
    applicable_question_types: ['mc', 'classify', 'short'],
    source: '教育局《小學常識科課程指引（2017）》',
  },
  {
    id: 'GS_P3_019',
    subject: '常識科',
    year: 'P3',
    topic: '環境與生活',
    unit: '資源節約與環保生活',
    knowledge_point: '使用公共交通工具的環保意義',
    learning_objective: '了解使用公共交通工具相比私家車對環境的好處，包括減少廢氣排放、節省能源及減少交通擠塞。',
    level: 1,
    applicable_question_types: ['mc', 'tf', 'short'],
    source: '教育局《小學常識科課程指引（2017）》',
  },
  // ── 範疇三：理財與經濟 ──────────────────────────────────────────
  {
    id: 'GS_P3_020',
    subject: '常識科',
    year: 'P3',
    topic: '理財與經濟',
    unit: '消費與理財基礎',
    knowledge_point: '需要與想要的區分及消費決定',
    learning_objective: '分辨「需要」（生活必需品）與「想要」（非必需的欲望），並能根據輕重緩急作出合理的消費決定，培養理性消費習慣。',
    level: 1,
    applicable_question_types: ['mc', 'tf', 'fill', 'short'],
    source: '教育局《小學常識科課程指引（2017）》',
  },
  {
    id: 'GS_P3_021',
    subject: '常識科',
    year: 'P3',
    topic: '理財與經濟',
    unit: '消費與理財基礎',
    knowledge_point: '消費者的基本權利與義務',
    learning_objective: '了解消費者享有的基本權利（如獲得安全產品、準確資訊、公平交易等）及應盡的義務（如誠實付款、合理使用商品等）。',
    level: 1,
    applicable_question_types: ['mc', 'tf', 'match', 'short'],
    source: '教育局《小學常識科課程指引（2017）》',
  },
  {
    id: 'GS_P3_022',
    subject: '常識科',
    year: 'P3',
    topic: '理財與經濟',
    unit: '消費與理財基礎',
    knowledge_point: '簡單儲蓄與金錢管理概念',
    learning_objective: '認識儲蓄的重要性，了解簡單的金錢管理方法，包括記錄收支、制定預算及養成儲蓄習慣。',
    level: 1,
    applicable_question_types: ['mc', 'fill', 'short'],
    source: '教育局《小學常識科課程指引（2017）》',
  },
  {
    id: 'GS_P3_023',
    subject: '常識科',
    year: 'P3',
    topic: '理財與經濟',
    unit: '消費與理財基礎',
    knowledge_point: '精明消費的考慮因素',
    learning_objective: '掌握精明消費的方法，包括比較價格與品質、查看產品標籤、認識消費者保障機構，以及避免衝動消費的策略。',
    level: 1,
    applicable_question_types: ['mc', 'tf', 'fill', 'short'],
    source: '教育局《小學常識科課程指引（2017）》',
  },
  {
    id: 'GS_P3_024',
    subject: '常識科',
    year: 'P3',
    topic: '理財與經濟',
    unit: '社區經濟與交易',
    knowledge_point: '社區常見交易場所與服務',
    learning_objective: '認識社區內不同類型的交易場所（如超級市場、街市、商場、網上商店等）及其特點，了解各種付款方式（現金、八達通、信用卡等）。',
    level: 1,
    applicable_question_types: ['mc', 'match', 'fill', 'classify'],
    source: '教育局《小學常識科課程指引（2017）》',
  },
  {
    id: 'GS_P3_025',
    subject: '常識科',
    year: 'P3',
    topic: '理財與經濟',
    unit: '社區經濟與交易',
    knowledge_point: '簡單買賣與找續計算',
    learning_objective: '能進行簡單的買賣計算，包括計算總價、找續金額，以及判斷是否得到正確找續，培養基本的數學應用能力。',
    level: 1,
    applicable_question_types: ['mc', 'fill', 'short'],
    source: '教育局《小學常識科課程指引（2017）》',
  },
  // ── 範疇四：社會與公民 ──────────────────────────────────────────
  {
    id: 'GS_P3_026',
    subject: '常識科',
    year: 'P3',
    topic: '社會與公民',
    unit: '家庭、學校與社區角色',
    knowledge_point: '家庭成員的角色與責任',
    learning_objective: '認識家庭成員各自的角色和責任，了解家庭成員之間互相關愛、分擔家務的重要性，培養對家庭的責任感。',
    level: 1,
    applicable_question_types: ['mc', 'match', 'short'],
    source: '教育局《小學常識科課程指引（2017）》',
  },
  {
    id: 'GS_P3_027',
    subject: '常識科',
    year: 'P3',
    topic: '社會與公民',
    unit: '家庭、學校與社區角色',
    knowledge_point: '學校生活中的規則與合作',
    learning_objective: '了解學校規則的重要性，認識在學校生活中與同學合作、互相尊重的方法，培養良好的公民意識。',
    level: 1,
    applicable_question_types: ['mc', 'tf', 'short'],
    source: '教育局《小學常識科課程指引（2017）》',
  },
  {
    id: 'GS_P3_028',
    subject: '常識科',
    year: 'P3',
    topic: '社會與公民',
    unit: '家庭、學校與社區角色',
    knowledge_point: '社區成員的互助與貢獻',
    learning_objective: '認識社區中不同成員（如義工、社區服務人員等）的貢獻，了解社區成員互助合作的重要性，培養服務社區的精神。',
    level: 1,
    applicable_question_types: ['mc', 'short', 'match'],
    source: '教育局《小學常識科課程指引（2017）》',
  },
  {
    id: 'GS_P3_029',
    subject: '常識科',
    year: 'P3',
    topic: '社會與公民',
    unit: '公民權利與責任',
    knowledge_point: '遵守規則與尊重他人的重要性',
    learning_objective: '了解在社會生活中遵守規則的重要性，認識尊重他人的具體表現，培養良好的公民品德和社會責任感。',
    level: 1,
    applicable_question_types: ['mc', 'tf', 'short'],
    source: '教育局《小學常識科課程指引（2017）》',
  },
  {
    id: 'GS_P3_030',
    subject: '常識科',
    year: 'P3',
    topic: '社會與公民',
    unit: '公民權利與責任',
    knowledge_point: '幫助他人與服務社區的意義',
    learning_objective: '了解幫助他人和服務社區的意義，認識義務工作的概念，培養關愛他人、回饋社會的精神。',
    level: 1,
    applicable_question_types: ['mc', 'tf', 'short'],
    source: '教育局《小學常識科課程指引（2017）》',
  },
  {
    id: 'GS_P3_031',
    subject: '常識科',
    year: 'P3',
    topic: '社會與公民',
    unit: '交通與公共服務',
    knowledge_point: '香港主要公共交通工具與使用方法',
    learning_objective: '認識香港主要的公共交通工具（港鐵、巴士、小巴、渡輪、電車、的士等），了解各種交通工具的特點、路線及購票/付款方式。',
    level: 1,
    applicable_question_types: ['mc', 'match', 'fill', 'classify'],
    source: '教育局《小學常識科課程指引（2017）》',
  },
  {
    id: 'GS_P3_032',
    subject: '常識科',
    year: 'P3',
    topic: '社會與公民',
    unit: '交通與公共服務',
    knowledge_point: '乘搭交通工具的安全守則與禮貌',
    learning_objective: '掌握乘搭各種交通工具時應遵守的安全守則（如扶穩手把、不把頭手伸出窗外等）及應有的禮貌行為（如讓座、排隊候車等）。',
    level: 1,
    applicable_question_types: ['mc', 'tf', 'fill', 'short'],
    source: '教育局《小學常識科課程指引（2017）》',
  },
  {
    id: 'GS_P3_033',
    subject: '常識科',
    year: 'P3',
    topic: '社會與公民',
    unit: '交通與公共服務',
    knowledge_point: '選擇合適交通工具的考慮因素',
    learning_objective: '能根據目的地、時間、費用、便利程度等因素，選擇最合適的交通工具，並能規劃簡單的交通路線。',
    level: 1,
    applicable_question_types: ['mc', 'tf', 'fill', 'short'],
    source: '教育局《小學常識科課程指引（2017）》',
  },
  // ── 範疇五：國家與我 ────────────────────────────────────────────
  {
    id: 'GS_P3_034',
    subject: '常識科',
    year: 'P3',
    topic: '國家與我',
    unit: '中華文化認識',
    knowledge_point: '中國傳統節日與習俗',
    learning_objective: '認識中國主要傳統節日（如農曆新年、中秋節、端午節等）的由來、習俗及慶祝方式，了解傳統節日對中華文化的意義。',
    level: 1,
    applicable_question_types: ['mc', 'match', 'fill', 'short'],
    source: '教育局《小學常識科課程指引（2017）》',
  },
  {
    id: 'GS_P3_035',
    subject: '常識科',
    year: 'P3',
    topic: '國家與我',
    unit: '中華文化認識',
    knowledge_point: '中華傳統美德與價值觀',
    learning_objective: '認識中華傳統美德（如孝順、誠信、勤勞、謙遜等），了解這些價值觀在現代生活中的意義，培養對中華文化的認同感。',
    level: 1,
    applicable_question_types: ['mc', 'tf', 'short'],
    source: '教育局《小學常識科課程指引（2017）》',
  },
  {
    id: 'GS_P3_036',
    subject: '常識科',
    year: 'P3',
    topic: '國家與我',
    unit: '中華文化認識',
    knowledge_point: '中國地理與著名景點初步認識',
    learning_objective: '初步認識中國的地理特色（如長江、黃河、長城等），了解部分著名景點的位置和特色，培養對祖國的認識和興趣。',
    level: 1,
    applicable_question_types: ['mc', 'match', 'fill', 'classify'],
    source: '教育局《小學常識科課程指引（2017）》',
  },
  {
    id: 'GS_P3_037',
    subject: '常識科',
    year: 'P3',
    topic: '國家與我',
    unit: '國家象徵與身份認同',
    knowledge_point: '國旗、國徽及國歌的意義',
    learning_objective: '認識中國國旗（五星紅旗）的設計含義、國徽的組成及國歌（義勇軍進行曲）的歷史背景，了解這些國家象徵的意義。',
    level: 1,
    applicable_question_types: ['mc', 'tf', 'fill', 'short'],
    source: '教育局《小學常識科課程指引（2017）》',
  },
  {
    id: 'GS_P3_038',
    subject: '常識科',
    year: 'P3',
    topic: '國家與我',
    unit: '國家象徵與身份認同',
    knowledge_point: '香港特別行政區的地位與特色',
    learning_objective: '了解香港作為中國特別行政區的地位，認識「一國兩制」的基本概念，了解香港的特色（如中西文化交融、國際金融中心等）。',
    level: 1,
    applicable_question_types: ['mc', 'tf', 'short'],
    source: '教育局《小學常識科課程指引（2017）》',
  },
  {
    id: 'GS_P3_039',
    subject: '常識科',
    year: 'P3',
    topic: '國家與我',
    unit: '國家象徵與身份認同',
    knowledge_point: '作為中國人的自豪感與責任',
    learning_objective: '培養對中國人身份的認同感和自豪感，了解作為中國公民的責任，包括愛護國家、遵守法律及為國家發展作出貢獻。',
    level: 1,
    applicable_question_types: ['mc', 'tf', 'short'],
    source: '教育局《小學常識科課程指引（2017）》',
  },
  // ── 範疇六：世界與我 ────────────────────────────────────────────
  {
    id: 'GS_P3_040',
    subject: '常識科',
    year: 'P3',
    topic: '世界與我',
    unit: '世界多元文化',
    knowledge_point: '世界主要國家與地區的初步認識',
    learning_objective: '初步認識世界主要國家和地區的位置、特色（如語言、文化、著名景點等），培養對世界的好奇心和探索精神。',
    level: 1,
    applicable_question_types: ['mc', 'match', 'fill', 'classify'],
    source: '教育局《小學常識科課程指引（2017）》',
  },
  {
    id: 'GS_P3_041',
    subject: '常識科',
    year: 'P3',
    topic: '世界與我',
    unit: '世界多元文化',
    knowledge_point: '尊重不同文化與習俗的重要性',
    learning_objective: '了解世界各地文化和習俗的多樣性，認識尊重不同文化的重要性，培養開放包容的態度和跨文化理解能力。',
    level: 1,
    applicable_question_types: ['mc', 'tf', 'short'],
    source: '教育局《小學常識科課程指引（2017）》',
  },
  {
    id: 'GS_P3_042',
    subject: '常識科',
    year: 'P3',
    topic: '世界與我',
    unit: '資訊科技與日常生活',
    knowledge_point: '資訊科技在日常生活中的應用',
    learning_objective: '認識資訊科技（如互聯網、智能手機、電腦等）在日常生活各方面的應用（學習、通訊、娛樂、購物等），了解使用資訊科技的注意事項。',
    level: 1,
    applicable_question_types: ['mc', 'tf', 'fill', 'short'],
    source: '教育局《小學常識科課程指引（2017）》',
  },
  {
    id: 'GS_P3_043',
    subject: '常識科',
    year: 'P3',
    topic: '世界與我',
    unit: '資訊科技與日常生活',
    knowledge_point: '安全使用資訊科技的基本守則',
    learning_objective: '了解安全使用資訊科技的基本守則，包括保護個人資料、設定安全密碼、避免接觸不良內容及控制使用時間等。',
    level: 1,
    applicable_question_types: ['mc', 'tf', 'short'],
    source: '教育局《小學常識科課程指引（2017）》',
  },
  {
    id: 'GS_P3_044',
    subject: '常識科',
    year: 'P3',
    topic: '世界與我',
    unit: '資訊科技與日常生活',
    knowledge_point: '辨識可靠資訊的初步能力',
    learning_objective: '培養初步辨識網絡資訊可靠性的能力，了解假新聞和錯誤資訊的危害，學習核實資訊的基本方法。',
    level: 1,
    applicable_question_types: ['mc', 'tf', 'short'],
    source: '教育局《小學常識科課程指引（2017）》',
  },
  {
    id: 'GS_P3_045',
    subject: '常識科',
    year: 'P3',
    topic: '世界與我',
    unit: '全球視野與議題',
    knowledge_point: '全球環境問題與個人行動',
    learning_objective: '初步認識全球環境問題（如氣候變化、海洋污染、森林砍伐等），了解這些問題對人類和地球的影響，認識個人可以採取的環保行動。',
    level: 1,
    applicable_question_types: ['mc', 'tf', 'short'],
    source: '教育局《小學常識科課程指引（2017）》',
  },
  {
    id: 'GS_P3_046',
    subject: '常識科',
    year: 'P3',
    topic: '世界與我',
    unit: '全球視野與議題',
    knowledge_point: '世界和平與合作的基本概念',
    learning_objective: '了解世界和平的重要性，認識國際合作（如聯合國）在解決全球問題中的作用，培養對世界和平的關注和責任感。',
    level: 1,
    applicable_question_types: ['mc', 'tf', 'short'],
    source: '教育局《小學常識科課程指引（2017）》',
  },
]

export function getKnowledgeByIds(ids: string[]): KnowledgeChunk[] {
  return KNOWLEDGE_BASE.filter(k => ids.includes(k.id))
}

// ── 中文科 P3 知識點（27 個）──────────────────────────────────────
// 來源：教育局《中國語文課程指引（小一至小六）》(2023)

export const CHINESE_P3_KNOWLEDGE: KnowledgeChunk[] = [
  // 範疇：聽 - 語音辨識
  {
    id: 'CH_P3_001',
    subject: '中文科',
    year: 'P3',
    topic: '聽',
    unit: '語音辨識',
    knowledge_point: '辨識漢語拼音的聲母、韻母和聲調',
    learning_objective: '培養正確的語音辨識能力',
    level: 1,
    applicable_question_types: ['mc', 'fill', 'tf'],
    source: '教育局《中國語文課程指引（小一至小六）》(2023)',
  },
  {
    id: 'CH_P3_002',
    subject: '中文科',
    year: 'P3',
    topic: '聽',
    unit: '語音辨識',
    knowledge_point: '區分同音字和近音字',
    learning_objective: '能分辨同音或近音字詞的意義差異',
    level: 1,
    applicable_question_types: ['mc', 'fill', 'tf', 'match'],
    source: '教育局《中國語文課程指引（小一至小六）》(2023)',
  },
  {
    id: 'CH_P3_003',
    subject: '中文科',
    year: 'P3',
    topic: '聽',
    unit: '語音辨識',
    knowledge_point: '聽辨語氣和語調變化',
    learning_objective: '能分辨不同語氣和語調所表達的情感或意圖',
    level: 1,
    applicable_question_types: ['mc', 'tf', 'short'],
    source: '教育局《中國語文課程指引（小一至小六）》(2023)',
  },
  // 範疇：聽 - 聽力理解
  {
    id: 'CH_P3_004',
    subject: '中文科',
    year: 'P3',
    topic: '聽',
    unit: '聽力理解',
    knowledge_point: '聽懂簡單日常對話和指令',
    learning_objective: '能理解日常對話和簡單指令的主要內容',
    level: 1,
    applicable_question_types: ['mc', 'fill', 'tf', 'short'],
    source: '教育局《中國語文課程指引（小一至小六）》(2023)',
  },
  {
    id: 'CH_P3_005',
    subject: '中文科',
    year: 'P3',
    topic: '聽',
    unit: '聽力理解',
    knowledge_point: '提取聽力材料的主要信息和細節',
    learning_objective: '能提取故事或短文的主要信息和關鍵細節',
    level: 1,
    applicable_question_types: ['mc', 'fill', 'tf'],
    source: '教育局《中國語文課程指引（小一至小六）》(2023)',
  },
  {
    id: 'CH_P3_006',
    subject: '中文科',
    year: 'P3',
    topic: '聽',
    unit: '聽力理解',
    knowledge_point: '根據聽力內容進行簡單推理',
    learning_objective: '能根據聽力內容進行簡單推理和判斷',
    level: 1,
    applicable_question_types: ['mc', 'tf', 'short'],
    source: '教育局《中國語文課程指引（小一至小六）》(2023)',
  },
  // 範疇：說 - 口頭表達
  {
    id: 'CH_P3_007',
    subject: '中文科',
    year: 'P3',
    topic: '說',
    unit: '口頭表達',
    knowledge_point: '清晰發音並控制適當語速',
    learning_objective: '能清晰發音並控制語速進行表達',
    level: 1,
    applicable_question_types: ['short', 'match'],
    source: '教育局《中國語文課程指引（小一至小六）》(2023)',
  },
  {
    id: 'CH_P3_008',
    subject: '中文科',
    year: 'P3',
    topic: '說',
    unit: '口頭表達',
    knowledge_point: '使用適當詞彙和句式表達想法',
    learning_objective: '能運用適當詞彙和句式清楚表達想法',
    level: 1,
    applicable_question_types: ['short', 'scenario'],
    source: '教育局《中國語文課程指引（小一至小六）》(2023)',
  },
  {
    id: 'CH_P3_009',
    subject: '中文科',
    year: 'P3',
    topic: '說',
    unit: '口頭表達',
    knowledge_point: '組織簡單內容進行口頭講述',
    learning_objective: '能組織簡單內容進行有條理的口頭講述',
    level: 1,
    applicable_question_types: ['short', 'scenario'],
    source: '教育局《中國語文課程指引（小一至小六）》(2023)',
  },
  // 範疇：說 - 對話交流
  {
    id: 'CH_P3_010',
    subject: '中文科',
    year: 'P3',
    topic: '說',
    unit: '對話交流',
    knowledge_point: '禮貌輪流發言並回應他人',
    learning_objective: '能在對話中禮貌輪流發言並適當回應',
    level: 1,
    applicable_question_types: ['scenario', 'short', 'tf'],
    source: '教育局《中國語文課程指引（小一至小六）》(2023)',
  },
  {
    id: 'CH_P3_011',
    subject: '中文科',
    year: 'P3',
    topic: '說',
    unit: '對話交流',
    knowledge_point: '提出問題並清楚回答',
    learning_objective: '能提出適切問題並清楚回答問題',
    level: 1,
    applicable_question_types: ['scenario', 'short'],
    source: '教育局《中國語文課程指引（小一至小六）》(2023)',
  },
  {
    id: 'CH_P3_012',
    subject: '中文科',
    year: 'P3',
    topic: '說',
    unit: '對話交流',
    knowledge_point: '表達意見並尊重不同觀點',
    learning_objective: '能表達個人意見並尊重他人觀點',
    level: 1,
    applicable_question_types: ['scenario', 'short', 'tf'],
    source: '教育局《中國語文課程指引（小一至小六）》(2023)',
  },
  // 範疇：讀 - 識字與詞彙
  {
    id: 'CH_P3_013',
    subject: '中文科',
    year: 'P3',
    topic: '讀',
    unit: '識字與詞彙',
    knowledge_point: '認讀小三程度常用漢字和詞語',
    learning_objective: '能認讀並書寫小三程度常用漢字和詞語',
    level: 1,
    applicable_question_types: ['mc', 'fill', 'match'],
    source: '教育局《中國語文課程指引（小一至小六）》(2023)',
  },
  {
    id: 'CH_P3_014',
    subject: '中文科',
    year: 'P3',
    topic: '讀',
    unit: '識字與詞彙',
    knowledge_point: '理解詞語在上下文中的意思和用法',
    learning_objective: '能根據上下文理解詞語的意思和用法',
    level: 1,
    applicable_question_types: ['mc', 'fill', 'tf', 'short'],
    source: '教育局《中國語文課程指引（小一至小六）》(2023)',
  },
  {
    id: 'CH_P3_015',
    subject: '中文科',
    year: 'P3',
    topic: '讀',
    unit: '識字與詞彙',
    knowledge_point: '認識並運用小三常見成語',
    learning_objective: '能認識並在適當情境中運用小三常見成語',
    level: 1,
    applicable_question_types: ['mc', 'fill', 'match', 'short'],
    source: '教育局《中國語文課程指引（小一至小六）》(2023)',
  },
  {
    id: 'CH_P3_016',
    subject: '中文科',
    year: 'P3',
    topic: '讀',
    unit: '識字與詞彙',
    knowledge_point: '辨識並理解比喻和擬人等簡單修辭手法',
    learning_objective: '能辨識並理解比喻、擬人等簡單修辭手法',
    level: 1,
    applicable_question_types: ['mc', 'tf', 'short'],
    source: '教育局《中國語文課程指引（小一至小六）》(2023)',
  },
  // 範疇：讀 - 閱讀理解
  {
    id: 'CH_P3_017',
    subject: '中文科',
    year: 'P3',
    topic: '讀',
    unit: '閱讀理解',
    knowledge_point: '理解100-200字短文的主要意思',
    learning_objective: '能理解100-200字短文的主要意思和中心思想',
    level: 1,
    applicable_question_types: ['mc', 'fill', 'tf', 'short'],
    source: '教育局《中國語文課程指引（小一至小六）》(2023)',
  },
  {
    id: 'CH_P3_018',
    subject: '中文科',
    year: 'P3',
    topic: '讀',
    unit: '閱讀理解',
    knowledge_point: '找出短文中的關鍵細節信息',
    learning_objective: '能從短文中找出關鍵細節和支持性信息',
    level: 1,
    applicable_question_types: ['mc', 'fill', 'tf'],
    source: '教育局《中國語文課程指引（小一至小六）》(2023)',
  },
  {
    id: 'CH_P3_019',
    subject: '中文科',
    year: 'P3',
    topic: '讀',
    unit: '閱讀理解',
    knowledge_point: '進行簡單的內容推理和預測',
    learning_objective: '能根據短文內容進行簡單推理、預測或判斷',
    level: 1,
    applicable_question_types: ['mc', 'tf', 'short'],
    source: '教育局《中國語文課程指引（小一至小六）》(2023)',
  },
  // 範疇：讀 - 標點符號
  {
    id: 'CH_P3_020',
    subject: '中文科',
    year: 'P3',
    topic: '讀',
    unit: '標點符號',
    knowledge_point: '辨識常用標點符號在閱讀中的作用',
    learning_objective: '能辨識逗號、句號、問號、感嘆號等標點符號的作用',
    level: 1,
    applicable_question_types: ['mc', 'tf', 'fill'],
    source: '教育局《中國語文課程指引（小一至小六）》(2023)',
  },
  // 範疇：寫 - 句子寫作
  {
    id: 'CH_P3_021',
    subject: '中文科',
    year: 'P3',
    topic: '寫',
    unit: '句子寫作',
    knowledge_point: '寫出意思完整、結構正確的簡單句子',
    learning_objective: '能寫出意思完整、結構正確的簡單句子',
    level: 1,
    applicable_question_types: ['fill', 'reorder', 'short'],
    source: '教育局《中國語文課程指引（小一至小六）》(2023)',
  },
  {
    id: 'CH_P3_022',
    subject: '中文科',
    year: 'P3',
    topic: '寫',
    unit: '句子寫作',
    knowledge_point: '正確使用標點符號寫句子',
    learning_objective: '能在句子中正確使用常用標點符號',
    level: 1,
    applicable_question_types: ['punctuation', 'fill', 'reorder'],
    source: '教育局《中國語文課程指引（小一至小六）》(2023)',
  },
  {
    id: 'CH_P3_023',
    subject: '中文科',
    year: 'P3',
    topic: '寫',
    unit: '句子寫作',
    knowledge_point: '重組詞語或句子使表達通順',
    learning_objective: '能重組詞語或句子，使意思通順完整',
    level: 1,
    applicable_question_types: ['reorder', 'arrange', 'fill'],
    source: '教育局《中國語文課程指引（小一至小六）》(2023)',
  },
  // 範疇：寫 - 段落組織
  {
    id: 'CH_P3_024',
    subject: '中文科',
    year: 'P3',
    topic: '寫',
    unit: '段落組織',
    knowledge_point: '寫出有中心意思的短段落（3-5句）',
    learning_objective: '能組織3-5句寫出有中心意思的短段落',
    level: 1,
    applicable_question_types: ['short', 'fill'],
    source: '教育局《中國語文課程指引（小一至小六）》(2023)',
  },
  {
    id: 'CH_P3_025',
    subject: '中文科',
    year: 'P3',
    topic: '寫',
    unit: '段落組織',
    knowledge_point: '使段落內句子連貫通順',
    learning_objective: '能運用適當連接使段落內句子連貫通順',
    level: 1,
    applicable_question_types: ['short', 'fill', 'tf'],
    source: '教育局《中國語文課程指引（小一至小六）》(2023)',
  },
  // 範疇：寫 - 標點運用
  {
    id: 'CH_P3_026',
    subject: '中文科',
    year: 'P3',
    topic: '寫',
    unit: '標點運用',
    knowledge_point: '在寫作中正確運用常用標點符號',
    learning_objective: '能在短段落寫作中正確運用常用標點符號',
    level: 1,
    applicable_question_types: ['punctuation', 'fill', 'short'],
    source: '教育局《中國語文課程指引（小一至小六）》(2023)',
  },
  {
    id: 'CH_P3_027',
    subject: '中文科',
    year: 'P3',
    topic: '寫',
    unit: '標點運用',
    knowledge_point: '避免寫作中常見的標點錯誤',
    learning_objective: '能辨識並改正寫作中常見的標點符號使用錯誤',
    level: 1,
    applicable_question_types: ['punctuation', 'tf', 'fill'],
    source: '教育局《中國語文課程指引（小一至小六）》(2023)',
  },
]

// ── 科學科 P3 知識點（21 個）──────────────────────────────────────
// 來源：教育局《科學（小一至小六）課程指引》（2025）

export const SCIENCE_P3_KNOWLEDGE: KnowledgeChunk[] = [
  // 範疇：科學探究
  {
    id: 'SCI_P3_001',
    subject: '科學科',
    year: 'P3',
    topic: '科學探究',
    unit: '科學探究',
    knowledge_point: '觀察物體特性並進行簡單描述',
    learning_objective: '能識別並描述物體的特性',
    level: 1,
    applicable_question_types: ['mc', 'picture_tf', 'fill', 'classify'],
    source: '教育局《科學（小一至小六）課程指引》（2025）',
  },
  {
    id: 'SCI_P3_002',
    subject: '科學科',
    year: 'P3',
    topic: '科學探究',
    unit: '科學探究',
    knowledge_point: '提出簡單的科學問題',
    learning_objective: '能基於觀察提出簡單科學問題',
    level: 1,
    applicable_question_types: ['short', 'scenario', 'mc'],
    source: '教育局《科學（小一至小六）課程指引》（2025）',
  },
  {
    id: 'SCI_P3_003',
    subject: '科學科',
    year: 'P3',
    topic: '科學探究',
    unit: '科學探究',
    knowledge_point: '進行簡單觀察或測試並記錄結果',
    learning_objective: '能以文字、圖畫或簡單表格記錄結果',
    level: 1,
    applicable_question_types: ['short', 'fill', 'picture_tf', 'classify'],
    source: '教育局《科學（小一至小六）課程指引》（2025）',
  },
  {
    id: 'SCI_P3_004',
    subject: '科學科',
    year: 'P3',
    topic: '科學探究',
    unit: '科學探究',
    knowledge_point: '根據觀察結果進行簡單分類',
    learning_objective: '能根據觀察到的特性進行簡單分類',
    level: 1,
    applicable_question_types: ['classify', 'match', 'mc', 'picture_tf'],
    source: '教育局《科學（小一至小六）課程指引》（2025）',
  },
  {
    id: 'SCI_P3_005',
    subject: '科學科',
    year: 'P3',
    topic: '科學探究',
    unit: '科學探究',
    knowledge_point: '根據證據得出簡單結論',
    learning_objective: '能根據證據得出簡單結論並解釋原因',
    level: 1,
    applicable_question_types: ['short', 'scenario', 'mc', 'tf'],
    source: '教育局《科學（小一至小六）課程指引》（2025）',
  },
  // 範疇：物理科學
  {
    id: 'SCI_P3_006',
    subject: '科學科',
    year: 'P3',
    topic: '物理科學',
    unit: '物理科學',
    knowledge_point: '光與影的形成條件和變化',
    learning_objective: '能描述光源、物體與影子的關係及變化',
    level: 1,
    applicable_question_types: ['mc', 'picture_tf', 'fill', 'short'],
    source: '教育局《科學（小一至小六）課程指引》（2025）',
  },
  {
    id: 'SCI_P3_007',
    subject: '科學科',
    year: 'P3',
    topic: '物理科學',
    unit: '物理科學',
    knowledge_point: '聲音的產生和傳播',
    learning_objective: '能描述振動產生聲音及聲音的傳播',
    level: 1,
    applicable_question_types: ['mc', 'picture_tf', 'fill', 'scenario'],
    source: '教育局《科學（小一至小六）課程指引》（2025）',
  },
  {
    id: 'SCI_P3_008',
    subject: '科學科',
    year: 'P3',
    topic: '物理科學',
    unit: '物理科學',
    knowledge_point: '熱的傳遞方式',
    learning_objective: '能識別傳導、對流和輻射及日常生活例子',
    level: 1,
    applicable_question_types: ['mc', 'picture_tf', 'match', 'classify'],
    source: '教育局《科學（小一至小六）課程指引》（2025）',
  },
  {
    id: 'SCI_P3_009',
    subject: '科學科',
    year: 'P3',
    topic: '物理科學',
    unit: '物理科學',
    knowledge_point: '簡單力與運動',
    learning_objective: '能描述推力、拉力及摩擦力對物體運動的影響',
    level: 1,
    applicable_question_types: ['mc', 'picture_tf', 'fill', 'short'],
    source: '教育局《科學（小一至小六）課程指引》（2025）',
  },
  {
    id: 'SCI_P3_010',
    subject: '科學科',
    year: 'P3',
    topic: '物理科學',
    unit: '物理科學',
    knowledge_point: '物質狀態變化',
    learning_objective: '能觀察並描述固體、液體、氣體之間的簡單變化',
    level: 1,
    applicable_question_types: ['mc', 'picture_tf', 'fill', 'classify'],
    source: '教育局《科學（小一至小六）課程指引》（2025）',
  },
  {
    id: 'SCI_P3_011',
    subject: '科學科',
    year: 'P3',
    topic: '物理科學',
    unit: '物理科學',
    knowledge_point: '電的初步認識',
    learning_objective: '能識別導體與絕緣體，了解簡單電路',
    level: 1,
    applicable_question_types: ['mc', 'picture_tf', 'match', 'scenario'],
    source: '教育局《科學（小一至小六）課程指引》（2025）',
  },
  // 範疇：生物科學
  {
    id: 'SCI_P3_012',
    subject: '科學科',
    year: 'P3',
    topic: '生物科學',
    unit: '生物科學',
    knowledge_point: '植物生長的需要和過程',
    learning_objective: '能描述植物生長所需的條件及簡單過程',
    level: 1,
    applicable_question_types: ['mc', 'picture_tf', 'fill', 'short'],
    source: '教育局《科學（小一至小六）課程指引》（2025）',
  },
  {
    id: 'SCI_P3_013',
    subject: '科學科',
    year: 'P3',
    topic: '生物科學',
    unit: '生物科學',
    knowledge_point: '動物的特徵和適應',
    learning_objective: '能描述常見動物的外部特徵及如何適應環境',
    level: 1,
    applicable_question_types: ['mc', 'picture_tf', 'match', 'classify'],
    source: '教育局《科學（小一至小六）課程指引》（2025）',
  },
  {
    id: 'SCI_P3_014',
    subject: '科學科',
    year: 'P3',
    topic: '生物科學',
    unit: '生物科學',
    knowledge_point: '人體的基本結構和功能',
    learning_objective: '能識別主要身體部位及其基本功能',
    level: 1,
    applicable_question_types: ['mc', 'picture_tf', 'fill', 'match'],
    source: '教育局《科學（小一至小六）課程指引》（2025）',
  },
  {
    id: 'SCI_P3_015',
    subject: '科學科',
    year: 'P3',
    topic: '生物科學',
    unit: '生物科學',
    knowledge_point: '生物與環境的互動',
    learning_objective: '能描述簡單食物鏈及生物如何依賴環境',
    level: 1,
    applicable_question_types: ['mc', 'picture_tf', 'classify', 'scenario'],
    source: '教育局《科學（小一至小六）課程指引》（2025）',
  },
  {
    id: 'SCI_P3_016',
    subject: '科學科',
    year: 'P3',
    topic: '生物科學',
    unit: '生物科學',
    knowledge_point: '保護生物多樣性與環境',
    learning_objective: '能認識保護生物和環境的重要性及簡單方法',
    level: 1,
    applicable_question_types: ['mc', 'picture_tf', 'short', 'scenario'],
    source: '教育局《科學（小一至小六）課程指引》（2025）',
  },
  // 範疇：地球科學
  {
    id: 'SCI_P3_017',
    subject: '科學科',
    year: 'P3',
    topic: '地球科學',
    unit: '地球科學',
    knowledge_point: '天氣現象的觀察和記錄',
    learning_objective: '能觀察並記錄常見天氣現象及其對生活的影響',
    level: 1,
    applicable_question_types: ['mc', 'picture_tf', 'fill', 'short'],
    source: '教育局《科學（小一至小六）課程指引》（2025）',
  },
  {
    id: 'SCI_P3_018',
    subject: '科學科',
    year: 'P3',
    topic: '地球科學',
    unit: '地球科學',
    knowledge_point: '太陽、地球與月亮的運動',
    learning_objective: '能描述日夜交替、影子變化及月相的簡單規律',
    level: 1,
    applicable_question_types: ['mc', 'picture_tf', 'fill', 'scenario'],
    source: '教育局《科學（小一至小六）課程指引》（2025）',
  },
  {
    id: 'SCI_P3_019',
    subject: '科學科',
    year: 'P3',
    topic: '地球科學',
    unit: '地球科學',
    knowledge_point: '水循環的基本過程',
    learning_objective: '能描述蒸發、凝結和降水等基本過程',
    level: 1,
    applicable_question_types: ['mc', 'picture_tf', 'fill', 'classify'],
    source: '教育局《科學（小一至小六）課程指引》（2025）',
  },
  {
    id: 'SCI_P3_020',
    subject: '科學科',
    year: 'P3',
    topic: '地球科學',
    unit: '地球科學',
    knowledge_point: '自然資源的種類和保護',
    learning_objective: '能識別常見自然資源並了解保護的重要性',
    level: 1,
    applicable_question_types: ['mc', 'picture_tf', 'match', 'short'],
    source: '教育局《科學（小一至小六）課程指引》（2025）',
  },
  {
    id: 'SCI_P3_021',
    subject: '科學科',
    year: 'P3',
    topic: '地球科學',
    unit: '地球科學',
    knowledge_point: '環境變化對生活的影響',
    learning_objective: '能描述天氣或資源變化對人類生活的簡單影響',
    level: 1,
    applicable_question_types: ['mc', 'picture_tf', 'scenario', 'short'],
    source: '教育局《科學（小一至小六）課程指引》（2025）',
  },
]

// 合併所有知識點到 KNOWLEDGE_BASE（追加）
KNOWLEDGE_BASE.push(...CHINESE_P3_KNOWLEDGE, ...SCIENCE_P3_KNOWLEDGE)

// ============================================================
// 英文科 P3 知識點（32個，4大範疇）
// 來源：English Language Curriculum Guide (Primary 1-6)
// ============================================================
export const ENGLISH_P3_KNOWLEDGE: KnowledgeChunk[] = [
  { id: 'EN_P3_001', subject: '英文科', year: 'P3', topic: 'Vocabulary', unit: 'Daily Vocabulary', knowledge_point: 'Family members and relationships', learning_objective: 'Talk about family members and relationships', level: 1, applicable_question_types: ['mc', 'fill', 'match'], source: 'English Language Curriculum Guide (Primary 1-6)' },
  { id: 'EN_P3_002', subject: '英文科', year: 'P3', topic: 'Vocabulary', unit: 'Daily Vocabulary', knowledge_point: 'School life and classroom objects', learning_objective: 'Describe school subjects, activities and classroom objects', level: 1, applicable_question_types: ['mc', 'fill', 'match'], source: 'English Language Curriculum Guide (Primary 1-6)' },
  { id: 'EN_P3_003', subject: '英文科', year: 'P3', topic: 'Vocabulary', unit: 'Daily Vocabulary', knowledge_point: 'Food, drinks and meals', learning_objective: 'Talk about food, drinks and daily meals', level: 1, applicable_question_types: ['mc', 'fill', 'match'], source: 'English Language Curriculum Guide (Primary 1-6)' },
  { id: 'EN_P3_004', subject: '英文科', year: 'P3', topic: 'Vocabulary', unit: 'Thematic Vocabulary', knowledge_point: 'Hobbies and free time activities', learning_objective: 'Describe hobbies and leisure activities', level: 1, applicable_question_types: ['mc', 'fill', 'match'], source: 'English Language Curriculum Guide (Primary 1-6)' },
  { id: 'EN_P3_005', subject: '英文科', year: 'P3', topic: 'Vocabulary', unit: 'Thematic Vocabulary', knowledge_point: 'Weather and seasons', learning_objective: 'Describe weather conditions and seasons', level: 1, applicable_question_types: ['mc', 'fill', 'match'], source: 'English Language Curriculum Guide (Primary 1-6)' },
  { id: 'EN_P3_006', subject: '英文科', year: 'P3', topic: 'Vocabulary', unit: 'Thematic Vocabulary', knowledge_point: 'Animals and pets', learning_objective: 'Describe common animals and pets', level: 1, applicable_question_types: ['mc', 'fill', 'match'], source: 'English Language Curriculum Guide (Primary 1-6)' },
  { id: 'EN_P3_007', subject: '英文科', year: 'P3', topic: 'Vocabulary', unit: 'Word Meaning and Collocations', knowledge_point: 'Simple opposites and synonyms', learning_objective: 'Understand and use simple opposites and synonyms in context', level: 1, applicable_question_types: ['mc', 'fill', 'match'], source: 'English Language Curriculum Guide (Primary 1-6)' },
  { id: 'EN_P3_008', subject: '英文科', year: 'P3', topic: 'Vocabulary', unit: 'Word Meaning and Collocations', knowledge_point: 'Common verb-noun collocations', learning_objective: 'Use common collocations (have breakfast, play football, go to school)', level: 1, applicable_question_types: ['mc', 'fill', 'match'], source: 'English Language Curriculum Guide (Primary 1-6)' },
  { id: 'EN_P3_009', subject: '英文科', year: 'P3', topic: 'Grammar', unit: 'Tenses', knowledge_point: 'Present simple tense for routines and facts', learning_objective: 'Use present simple tense to talk about daily routines, habits and facts', level: 1, applicable_question_types: ['mc', 'fill', 'tf', 'match'], source: 'English Language Curriculum Guide (Primary 1-6)' },
  { id: 'EN_P3_010', subject: '英文科', year: 'P3', topic: 'Grammar', unit: 'Tenses', knowledge_point: 'Present continuous tense for actions happening now', learning_objective: 'Use present continuous tense to describe actions happening now', level: 1, applicable_question_types: ['mc', 'fill', 'tf'], source: 'English Language Curriculum Guide (Primary 1-6)' },
  { id: 'EN_P3_011', subject: '英文科', year: 'P3', topic: 'Grammar', unit: 'Tenses', knowledge_point: 'Past simple tense (regular verbs)', learning_objective: 'Use past simple tense with regular verbs for completed actions', level: 1, applicable_question_types: ['mc', 'fill', 'tf', 'reorder'], source: 'English Language Curriculum Guide (Primary 1-6)' },
  { id: 'EN_P3_012', subject: '英文科', year: 'P3', topic: 'Grammar', unit: 'Tenses', knowledge_point: 'Future tense with going to', learning_objective: 'Use going to to talk about future plans and intentions', level: 1, applicable_question_types: ['mc', 'fill', 'tf'], source: 'English Language Curriculum Guide (Primary 1-6)' },
  { id: 'EN_P3_013', subject: '英文科', year: 'P3', topic: 'Grammar', unit: 'Prepositions and Pronouns', knowledge_point: 'Prepositions of place and time', learning_objective: 'Use prepositions of place and time correctly', level: 1, applicable_question_types: ['mc', 'fill', 'match'], source: 'English Language Curriculum Guide (Primary 1-6)' },
  { id: 'EN_P3_014', subject: '英文科', year: 'P3', topic: 'Grammar', unit: 'Prepositions and Pronouns', knowledge_point: 'Personal and possessive pronouns', learning_objective: 'Use personal pronouns and possessive adjectives correctly', level: 1, applicable_question_types: ['mc', 'fill', 'tf', 'match'], source: 'English Language Curriculum Guide (Primary 1-6)' },
  { id: 'EN_P3_015', subject: '英文科', year: 'P3', topic: 'Grammar', unit: 'Prepositions and Pronouns', knowledge_point: 'Object pronouns', learning_objective: 'Use object pronouns in context', level: 1, applicable_question_types: ['mc', 'fill', 'match'], source: 'English Language Curriculum Guide (Primary 1-6)' },
  { id: 'EN_P3_016', subject: '英文科', year: 'P3', topic: 'Grammar', unit: 'Articles, Conjunctions and Question Words', knowledge_point: 'Articles a, an and the', learning_objective: 'Use articles correctly with nouns', level: 1, applicable_question_types: ['mc', 'fill', 'tf'], source: 'English Language Curriculum Guide (Primary 1-6)' },
  { id: 'EN_P3_017', subject: '英文科', year: 'P3', topic: 'Grammar', unit: 'Articles, Conjunctions and Question Words', knowledge_point: 'Conjunctions and, but, or and because', learning_objective: 'Use conjunctions to join ideas in sentences', level: 1, applicable_question_types: ['mc', 'fill', 'tf', 'reorder'], source: 'English Language Curriculum Guide (Primary 1-6)' },
  { id: 'EN_P3_018', subject: '英文科', year: 'P3', topic: 'Grammar', unit: 'Articles, Conjunctions and Question Words', knowledge_point: 'Question words who, what, where, when, why and how', learning_objective: 'Use question words to ask for information', level: 1, applicable_question_types: ['mc', 'fill', 'match'], source: 'English Language Curriculum Guide (Primary 1-6)' },
  { id: 'EN_P3_019', subject: '英文科', year: 'P3', topic: 'Reading', unit: 'Reading Comprehension', knowledge_point: 'Understanding the main idea of short texts', learning_objective: 'Understand the main idea of short passages (80-120 words)', level: 1, applicable_question_types: ['mc', 'tf', 'comprehension'], source: 'English Language Curriculum Guide (Primary 1-6)' },
  { id: 'EN_P3_020', subject: '英文科', year: 'P3', topic: 'Reading', unit: 'Reading Comprehension', knowledge_point: 'Identifying key details in short texts', learning_objective: 'Locate specific details in short reading passages', level: 1, applicable_question_types: ['mc', 'fill', 'comprehension'], source: 'English Language Curriculum Guide (Primary 1-6)' },
  { id: 'EN_P3_021', subject: '英文科', year: 'P3', topic: 'Reading', unit: 'Reading Comprehension', knowledge_point: 'Understanding vocabulary in context', learning_objective: 'Understand meaning of new words from context', level: 1, applicable_question_types: ['mc', 'match', 'comprehension'], source: 'English Language Curriculum Guide (Primary 1-6)' },
  { id: 'EN_P3_022', subject: '英文科', year: 'P3', topic: 'Reading', unit: 'Information Extraction', knowledge_point: 'Scanning for specific information', learning_objective: 'Find specific information quickly in short texts', level: 1, applicable_question_types: ['mc', 'tf', 'comprehension'], source: 'English Language Curriculum Guide (Primary 1-6)' },
  { id: 'EN_P3_023', subject: '英文科', year: 'P3', topic: 'Reading', unit: 'Information Extraction', knowledge_point: 'True or False statements based on text', learning_objective: 'Judge statements as true or false based on reading passages', level: 1, applicable_question_types: ['tf', 'comprehension'], source: 'English Language Curriculum Guide (Primary 1-6)' },
  { id: 'EN_P3_024', subject: '英文科', year: 'P3', topic: 'Reading', unit: 'Simple Inference', knowledge_point: 'Inferring feelings or reasons from context', learning_objective: "Infer characters' feelings or reasons from short texts", level: 1, applicable_question_types: ['mc', 'tf', 'comprehension'], source: 'English Language Curriculum Guide (Primary 1-6)' },
  { id: 'EN_P3_025', subject: '英文科', year: 'P3', topic: 'Reading', unit: 'Simple Inference', knowledge_point: 'Making simple predictions from text', learning_objective: 'Make simple predictions from a short story', level: 1, applicable_question_types: ['mc', 'comprehension'], source: 'English Language Curriculum Guide (Primary 1-6)' },
  { id: 'EN_P3_026', subject: '英文科', year: 'P3', topic: 'Writing', unit: 'Sentence Writing', knowledge_point: 'Constructing correct simple sentences', learning_objective: 'Write grammatically correct simple sentences', level: 1, applicable_question_types: ['mc', 'fill', 'reorder'], source: 'English Language Curriculum Guide (Primary 1-6)' },
  { id: 'EN_P3_027', subject: '英文科', year: 'P3', topic: 'Writing', unit: 'Sentence Writing', knowledge_point: 'Using adjectives to describe nouns', learning_objective: 'Use adjectives to make sentences more descriptive', level: 1, applicable_question_types: ['fill', 'mc', 'reorder'], source: 'English Language Curriculum Guide (Primary 1-6)' },
  { id: 'EN_P3_028', subject: '英文科', year: 'P3', topic: 'Writing', unit: 'Sentence Writing', knowledge_point: 'Subject-verb agreement in sentences', learning_objective: 'Apply basic subject-verb agreement', level: 1, applicable_question_types: ['mc', 'fill', 'tf'], source: 'English Language Curriculum Guide (Primary 1-6)' },
  { id: 'EN_P3_029', subject: '英文科', year: 'P3', topic: 'Writing', unit: 'Paragraph Organization', knowledge_point: 'Writing short paragraphs on familiar topics', learning_objective: 'Write a short paragraph of 3-5 sentences', level: 1, applicable_question_types: ['mc', 'fill'], source: 'English Language Curriculum Guide (Primary 1-6)' },
  { id: 'EN_P3_030', subject: '英文科', year: 'P3', topic: 'Writing', unit: 'Paragraph Organization', knowledge_point: 'Using conjunctions to connect ideas', learning_objective: 'Use conjunctions to link sentences in a short paragraph', level: 1, applicable_question_types: ['fill', 'reorder'], source: 'English Language Curriculum Guide (Primary 1-6)' },
  { id: 'EN_P3_031', subject: '英文科', year: 'P3', topic: 'Writing', unit: 'Punctuation and Capitalization', knowledge_point: 'Using full stops, question marks and exclamation marks', learning_objective: 'Use appropriate end punctuation in sentences', level: 1, applicable_question_types: ['mc', 'fill', 'tf'], source: 'English Language Curriculum Guide (Primary 1-6)' },
  { id: 'EN_P3_032', subject: '英文科', year: 'P3', topic: 'Writing', unit: 'Punctuation and Capitalization', knowledge_point: 'Capital letters for names, I and sentence beginnings', learning_objective: 'Use capital letters correctly', level: 1, applicable_question_types: ['mc', 'fill', 'tf'], source: 'English Language Curriculum Guide (Primary 1-6)' },
]

// 將英文科知識點追加至 KNOWLEDGE_BASE
KNOWLEDGE_BASE.push(...ENGLISH_P3_KNOWLEDGE)
